import Head from 'next/head'
// components
import Slider from '@/components/home/slider';
import Luncherbjudanden from '@/components/home/luncherbjudanden';
import News from '@/components/home/news';
import Dryckes from '@/components/home/dryckes';


export default function Home() {
  return (
    <>
      <Head>
        <title>Twins-Pizzeria</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full flex items-center justify-start flex-col pb-16">
        <Slider />
        <Luncherbjudanden />
        <News />
        <Dryckes />
      </main>
    </>
  )
}

Home.layout = "L1";